repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-merge-conflict
  - id: end-of-file-fixer
    exclude: ^.idea
  - id: mixed-line-ending
    args: [--fix=lf]
    exclude: \.bat$|^.idea
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
  - id: pretty-format-kotlin
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
