name: gradle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: adopt
    - uses: srt32/git-actions@v0.0.3
    - run: chmod +x gradlew
    - run: ./gradlew build
